### ISSUE TITLE
somafm gets muted if device screen off or another app in active focus

### ISSUE THREAD

**Issue by nebocamin** [DanOpcode/somafm-firefox-os-app#5]
hi,

I really like the app, because I use it a lot to hear music on my way to work and back. It was all good using my flame as device. now i started using a sony z3c [aries] using b2g ver2.5 and the music stops if I turn of the screen or click the home button or switch to another app. i can still see the network traffic streaming (the blinking icon) and top -m 5 still shows mediaserver running. If I switch back to the app, it is still nothing to hear until i close the somafm app and start it new.

I attach the adb logcat from starting the app, pressing play and clicking home...

If you have any ideas how I could help, please contact me ;o)

bye,
ralf

W/SomaFM  ( 2592): [JavaScript Warning: "Use of nsIFile in content process is deprecated." {file: "jar:file:///system/b2g/omni.ja!/components/DirectoryProvider.js" line: 81}]
W/SomaFM  ( 2592): [JavaScript Warning: "Expected end of selector or a user action pseudo-class after pseudo-element but found ':'.  Ruleset ignored due to bad selector." {file: "app://{1e357932-e2ee-4b48-a4e4-6725ba269066}/css/building-blocks/media_icons.css" line: 83 column: 25 source: ".media-artistfilter:after:before { background-position:  -0px -575px; }"}]
I/SomaFM  ( 2592): Content JS LOG: Initialize AppView 
I/SomaFM  ( 2592):     at app.AppView<.initialize (app://{1e357932-e2ee-4b48-a4e4-6725ba269066}/js/views/app-view.js:11:7)
W/GeckoConsole(  317): [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://marketplace.cdn.mozilla.net/icons/icon-60.png" line: 0}]
I/SomaFM  ( 2592): Content JS LOG: Playing cliqhop 
I/SomaFM  ( 2592):     at app.PlaybackView<.play (app://{1e357932-e2ee-4b48-a4e4-6725ba269066}/js/views/playback-view.js:73:7)
I/Gecko   ( 2984): ###################################### forms.js loaded
I/Gecko   ( 2984): ############################### browserElementPanning.js loaded
I/Gecko   ( 2984): ###################################### BrowserElementCopyPaste.js loaded
I/Gecko   ( 2984): ######################## BrowserElementChildPreload.js loaded
I/(Preallocated app)( 2984): PAC file installed from data: URI
E/WVMExtractor( 2592): Failed to open libwvm.so
D/ExtendedUtils( 2592): extended extractor not needed, return default
I/OMXClient( 2592): Using client-side OMX mux.
E/OMXCodec( 2592): Forcing SoftwareCodec for mime type audio/mpeg
E/OMXMaster( 2592): A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
W/AudioFlinger(  294): Thread AudioOut_2 cannot connect to the power manager service
W/AudioFlinger(  294): Thread AudioOut_3 cannot connect to the power manager service
W/AudioFlinger(  294): Thread AudioOut_3 cannot connect to the power manager service
E/AudioFlinger(  294): no wake lock to update!
W/AudioFlinger(  294): Thread AudioOut_2 cannot connect to the power manager service
E/AudioFlinger(  294): no wake lock to update!
I/SonySWEffect(  294): /system/etc/sforce/sforce_param_arm.bin : file open success, use File Parameter
D/SonySWEffect(  294): PARAM_CA_CHSEP Clear Stereo Off(0x0)
E/SonySWEffect(  294): clearphase_update_coef failed because mode is OFF
D/audio_hw_primary(  294): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=8
W/AudioFlinger(  294): Thread AudioOut_3 cannot connect to the power manager service
E/AudioFlinger(  294): no wake lock to update!
E/audio_hw_primary(  294): voice_extn_compress_voip_is_active: COMPRESS_VOIP_ENABLED is not defined
D/audio_hw_extn(  294): audio_extn_get_anc_enabled: anc_enabled:0
D/audio_hw_primary(  294): select_devices: out_snd_device(32: headphones) in_snd_device(0: )
D/hardware_info(  294): hw_info_append_hw_type : device_name = headphones
D/ACDB-LOADER(  294): ACDB -> send_audio_cal, acdb_id = 10, path =  0
D/ACDB-LOADER(  294): ACDB -> send_adm_topology
D/ACDB-LOADER(  294): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(  294): ACDB -> send_asm_topology
D/ACDB-LOADER(  294): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
D/ACDB-LOADER(  294): ACDB -> send_audtable
D/ACDB-LOADER(  294): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER(  294): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(  294): ACDB -> send_audvoltable
D/ACDB-LOADER(  294): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
D/ACDB-LOADER(  294): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(  294): ACDB -> AUDIO_SET_AFE_CAL
D/audio_hw_extn(  294): audio_extn_get_anc_enabled: anc_enabled:0
D/audio_hw_extn(  294): audio_extn_get_anc_enabled: anc_enabled:0
D/sony_audio_effect(  294): sony_update_effect_param: Same out device. No need to update
D/effect_intf(  294): add_active_usecase: id 1
D/effect_intf(  294): add_active_usecase: Add effect list, usecase ID 1
I/effect_intf(  294): store_effect_param: call
D/sony_audio_effect(  294): sony_get_effect_param: update flag = 0x007f,
D/sony_audio_effect(  294): sony_get_effect_param: Unsupported deivce. Disable effect xLOUD
D/sony_audio_effect(  294): sony_get_effect_param: Unsupported deivce. Disable effect ClearPhase
D/sony_audio_effect(  294): sony_get_effect_param: Unsupported deivce. Disable effect S-Force
D/sony_audio_effect(  294): sony_get_effect_param: count = 5
D/skia    ( 2592): START /proc/cpuinfo:
D/skia    ( 2592): Processor    : ARMv7 Processor rev 1 (v7l)
D/skia    ( 2592): processor    : 0
D/skia    ( 2592): BogoMIPS : 38.40
D/skia    ( 2592): 
D/skia    ( 2592): processor    : 1
D/skia    ( 2592): BogoMIPS : 38.40
D/skia    ( 2592): 
D/skia    ( 2592): processor    : 2
D/skia    ( 2592): BogoMIPS : 38.40
D/skia    ( 2592): 
D/skia    ( 2592): processor    : 3
D/skia    ( 2592): BogoMIPS : 38.40
D/skia    ( 2592): 
D/skia    ( 2592): Features : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
D/skia    ( 2592): CPU implementer  : 0x51
D/skia    ( 2592): CPU architecture: 7
D/skia    ( 2592): CPU variant  : 0x2
D/skia    ( 2592): CPU part : 0x06f
D/skia    ( 2592): CPU revision : 1
D/skia    ( 2592): 
D/skia    ( 2592): Hardware : Qualcomm MSM8974PRO-AC
D/skia    ( 2592): Revision : 0000
D/skia    ( 2592): Serial       : 0000000000000000
D/skia    ( 2592): 
D/skia    ( 2592): END /proc/cpuinfo
D/skia    ( 2592): Device supports ARM NEON instructions!
W/AudioFlinger(  294): Thread AudioOut_3 cannot connect to the power manager service
E/AudioFlinger(  294): no wake lock to update!
D/effect_intf(  294): remove_active_usecase: Remove effect handle, usecase ID 1
D/hardware_info(  294): hw_info_append_hw_type : device_name = headphones
D/audio_hw_extn(  294): audio_extn_get_anc_enabled: anc_enabled:0
^C

**Comment by nebocamin** [comment]
I tested the "dradio" app. its free software and it works. something is different there. 
https://github.com/opendradio/app

and i added the logcat from starting to play and blanking the screen.

D/sony_audio_effect(  294): sony_get_effect_param: update flag = 0x007f,
D/sony_audio_effect(  294): sony_get_effect_param: Unsupported deivce. Disable effect xLOUD
D/sony_audio_effect(  294): sony_get_effect_param: Unsupported deivce. Disable effect ClearPhase
D/sony_audio_effect(  294): sony_get_effect_param: Unsupported deivce. Disable effect S-Force
D/sony_audio_effect(  294): sony_get_effect_param: count = 5
E/Diag_Lib(  735): [IMS_FATAL]| 2992 | 791 |ims-rtp-daemon ims_rtp_qmi_handler_thread_func waiting on select thread>
D/qdhwcomposer(  317): hwc_blank: Blanking display: 0
I/qdhwcomposer(  317): handle_blank_event: dpy:0 panel power state: 0
D/qdhwcomposer(  317): hwc_blank: Done blanking display: 0
I/QCOM PowerHAL(  317): Got set_interactive hint
E/qdhwcomposer(  317): hwc_vsync_control: vsync control failed. Dpy=0, enable=1 : Operation not supported on transport endpoint
E/qdhwcomposer(  317): hwc_vsync_control: vsync control failed. Dpy=0, enable=1 : Operation not supported on transport endpoint
E/qdhwcomposer(  317): hwc_vsync_control: vsync control failed. Dpy=0, enable=1 : Operation not supported on transport endpoint
E/qdhwcomposer(  317): hwc_vsync_control: vsync control failed. Dpy=0, enable=1 : Operation not supported on transport endpoint
E/qdhwcomposer(  317): hwc_vsync_control: vsync control failed. Dpy=0, enable=1 : Operation not supported on transport endpoint
E/qdhwcomposer(  317): hwc_vsync_control: vsync control failed. Dpy=0, enable=1 : Operation not supported on transport endpoint
I/QCOM PowerHAL(  317): Got set_interactive hint
D/qdhwcomposer(  317): hwc_blank: Unblanking display: 0
I/qdhwcomposer(  317): handle_blank_event: dpy:0 panel power state: 1
D/qdhwcomposer(  317): hwc_blank: Done unblanking display: 0

**Comment by nebocamin** [comment]
maybe thats the reason? https://bugzilla.mozilla.org/show_bug.cgi?id=1200111

**Comment by DanOpcode** [comment]
Hi,

Sorry for ignoring you. I'm quite busy with part-time work and university studies.

When a channel is selected https://github.com/matachi/somafm-firefox-os-app/blob/trunk/src/js/views/channel-view.js#L29 it tells the playback model to play https://github.com/matachi/somafm-firefox-os-app/blob/trunk/src/js/models/playback.js#L17. The model then triggers an event, which the playback view listens to https://github.com/matachi/somafm-firefox-os-app/blob/trunk/src/js/views/playback-view.js#L71. The view then appends the URL of the stream to the template where the app's audio element resides https://github.com/matachi/somafm-firefox-os-app/blob/trunk/src/js/templates/playback.html#L4.

I believe this is not the proper way to play audio in the background. Maybe there's a better API that's more suited for the purpose.
